# Define the hazelcast-client-role and bind it to the application's service account

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hazelcast-client-role
  namespace: demo
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hazelcast-client-role-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: think-demo-hz
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hazelcast-client-role
