# Assumes the OpenLiberty operator has been installed in your cluster
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: think-demo-hz
spec:
  applicationImage: barecode/think-demo:1.0
  replicas: 2
  service:
    type: ClusterIP
    port: 9080
  expose: true
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: "basic"
