kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: think-demo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: think-demo
          image: >-
            barecode/think-demo
          ports:
            - containerPort: 9080
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: IfNotPresent
