kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hazelcast-client-demo
  namespace: demo
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
